In [2]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% !important;} 
div.cell.code_cell.rendered{width:100%;} 
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:14pt;} 
div.text_cell_render.rendered_html{font-size:14pt;} 
div.output {font-size:14pt; font-weight:bold;} 
div.input {font-family:Consolas; font-size:14pt;} 
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;} 
div.text_cell_render ul li{font-size:12pt;padding:5px;} 
table.dataframe{font-size:12px;}
</style>
"""))

<b><font size="6" color="red">ch10. N차원 배열(Numpy 배열) 다루기</font></b>
# 4절 복사와 뷰
## 4.1 할당

In [31]:
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
b = a

In [5]:
a.shape, a.ndim, id(a), type(a)

((12,), 1, 2090381325680, numpy.ndarray)

In [6]:
b.shape, b.ndim, id(b), type(b)

((12,), 1, 2090381325680, numpy.ndarray)

In [7]:
a is b    # 같은 객체면 true

True

In [9]:
np.all(a == b)

True

In [10]:
b.shape = (3,4) # 할당받은 b의 shape을 수정 

In [11]:
a.shape, a.ndim, id(a), type(a)

((3, 4), 2, 2090381325680, numpy.ndarray)

In [12]:
b.shape, b.ndim, id(b), type(b)

((3, 4), 2, 2090381325680, numpy.ndarray)

In [13]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 4.2 얕은복사 : 뷰(View)

In [15]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
c = a.view()     # 얕은 복사 - 틀만복사
print(id(a), id(c))

2090420333296 2090420334544


In [21]:
c == a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [23]:
c.shape = (2,6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [24]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
c[1,::2] = -99
c

array([[  0,   1,   2,   3,   4,   5],
       [-99,   7, -99,   9, -99,  11]])

In [28]:
a

array([[  0,   1,   2,   3],
       [  4,   5, -99,   7],
       [-99,   9, -99,  11]])

## 4.3 깊은 복사

In [29]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a = np.array([[5,  4, 13, 0],
              [99, 6, 16, 1],
              [20, 5, 14, 0]])
a

array([[ 5,  4, 13,  0],
       [99,  6, 16,  1],
       [20,  5, 14,  0]])

In [43]:
# X = a[:, :-1]  # 슬라이싱이 될 때, 뷰가 봔환됨(얕은 복사 - 창만 복사되는 것:원본데이터가 유지되지 못함)
X = a[:, :-1].copy()  # 깊은 복사
X = np.array(a[:, :-1], copy=True) # 거의 쓰이지 않는 방식
X

array([[ 5,  4, 13],
       [99,  6, 16],
       [20,  5, 14]])

In [44]:
X[:, 0] = -9
X

array([[-9,  4, 13],
       [-9,  6, 16],
       [-9,  5, 14]])

In [45]:
a

array([[ 5,  4, 13,  0],
       [99,  6, 16,  1],
       [20,  5, 14,  0]])

# 5절 고급인덱싱